# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad0b6e934627daa531493939f1be114f48a01d32441dac437791095d4cedc7e3b054871268e2a00e42ca80c14e0225d37559a1bfc45d955b773cff25f74a7915

test:
  secret_key_base: 356be6aae7f54d4d39133c3b3c0ef672fa5fd5d199758e089e57a3bb55c3b2c8a684dab63a4636931e6d3441059452cbbba92ed95fb590a88939dc1310557518

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
